activities: list = [
    "with Cosmo",
    "?cosmo",
    "RuneLite",
    "?help",
    "Fishing in Lumbridge",
    "Grand Exchange",
    "SMITE",
    "Overwatch 2",
    "?cat",
    "?bczs",
    "with Bartholomeow",
    "/waifu",
    "?year",
    "@Konikotaka",
    "with the API",
    "/weather",
    "Call of Duty: Modern Warfare",
    "Sea of Thieves",
    "Minecraft",
    "GenSHIN Impact",
]
