activities: list = [
    "with Cosmo",
    "?cosmo",
    "RuneLite",
    "?help",
    "Fishing in Lumbridge",
    "Grand Exchange",
    "SMITE",
    "Overwatch 2",
    "?cat",
    "?bczs",
    "with Bartholomeow",
    "/waifu",
    "?year",
    "@Konikotaka",
    "with the API",
    "/weather",
    "Call of Duty: Modern Warfare",
    "Sea of Thieves",
    "Minecraft",
    "GenSHIN Impact",
    "/imagine",
    "Team Fight Tactics",
    "League of Legends",
    "Fortnite",
]

ai_ban_words: list = [
    "Blood",
    "Bloodbath",
    "Crucifixion",
    "Bloody",
    "Flesh",
    "Bruises",
    "Corpse",
    "Crucified",
    "Cutting",
    "Decapitate",
    "Infested",
    "Gruesome",
    "Kill",
    "Infected",
    "Sadist",
    "Slaughter",
    "Teratoma",
    "Tryphophobia",
    "Wound",
    "Cronenberg",
    "Khorne",
    "Cannibal",
    "Cannibalism",
    "Visceral",
    "Guts",
    "Bloodshot",
    "Gory",
    "Killing",
    "Surgery",
    "Vivisection",
    "Massacre",
    "Hemoglobin",
    "Suicide",
    "Female",
    "Body Parts",
    "ahegao",
    "pinup",
    "ballgag",
    "Playboy",
    "Bimbo",
    "pleasure",
    "bodily",
    "fluids",
    "pleasures",
    "boudoir",
    "rule34",
    "brothel",
    "seducing",
    "dominatrix",
    "seductive",
    "erotic",
    "seductive",
    "fuck",
    "sensual",
    "Hardcore",
    "sexy",
    "Hentai",
    "Shag",
    "horny",
    "shibari",
    "incest",
    "Smut",
    "jav",
    "succubus",
    "Jerk",
    "thot",
    "kinbaku",
    "transparent",
    "legs",
    "spread",
    "twerk",
    "making",
    "love",
    "voluptuous",
    "naughty",
    "wincest",
    "orgy",
    "Sultry",
    "XXX",
    "Bondage",
    "Bdsm",
    "collar",
    "Slavegirl",
    "Transparent",
    "Translucent",
    "Speedo",
    "nude",
    "bra",
    "risqué",
    "clear",
    "scantily",
    "clad",
    "cleavage",
    "stripped",
    "unclothed",
    "invisible",
    "lingerie",
    "naked",
    "negligee",
    "Taboo",
    "Fascist",
    "Nazi",
    "Slave",
    "Coon",
    "Honkey",
    "Arrested",
    "Jail",
    "Handcuffs",
    "Torture",
    "Disturbing",
    "Farts",
    "Fart",
    "Poop",
    "Warts",
    "Xi Jinping",
    "Shit",
    "Pleasure",
    "Errect",
    "Big Black",
    "Bunghole",
    "Vomit",
    "Voluptuous",
    "Seductive",
    "Sperm",
]
