activities = [
    "with Cosmo",
    "?cosmo",
    "RuneLite",
    "?help",
    "Fishing in Lumbridge",
    "Grand Exchange",
    "SMITE",
    "Overwatch 2",
    "?cat",
    "?bczs",
    "with Bartholomeow",
    "Annoying Seaira",
    "/newpet",
    "/waifu",
    "?year",
]
